stages:
  - build

job:
  stage: build
  script:
  - echo "Restoring NuGet Packages..."
  - '"c:\nuget\nuget.exe" restore "resources/Clanbutton/Clanbutton.sln"'
  - ''
  - echo "Release build..."
  - C:\PROGRA~1\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe resources/Clanbutton/Clanbutton.sln
  tags: 
  except:
  - tags
