stages:
  - build

job:
  stage: build
  script:
  - echo "Restoring NuGet Packages..."
  - '"c:\nuget\nuget.exe" restore "C:\Users\alexn\Desktop\2019-ca326-clanbutton\Project\resources\Clanbutton\Clanbutton.sln"'
  - ''
  - echo "Release build..."
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe" "C:\Users\alexn\Desktop\2019-ca326-clanbutton\Project\resources\Clanbutton\Clanbutton.sln"'
  tags: 
  except:
  - tags
